USE [990000278_Merricks];
--USE [5377_WEIGAND_II_R2];
GO

CREATE OR ALTER PROCEDURE filevine.usp_insert_reference_ContactCustomFieldMetadata
	@DEBUGFLAG             BIT,
	@DATABASE              VARCHAR(1000),
	@SCHEMANAME            VARCHAR(1000),
	@FVPRODUCTIONPREFIX    VARCHAR(1000),
	@TIMEZONE              VARCHAR(1000)
AS
BEGIN

	DROP TABLE IF EXISTS 
		DBO.__FV_CONTACTCUSTOMFIELDMETADATA;

	CREATE TABLE [dbo].[__FV_ContactCustomFieldMetadata]
	(
		PERSONID         VARCHAR(MAX) NULL,
		TAB              VARCHAR(MAX) NOT NULL,
		FIELDPOSITION    VARCHAR(MAX) NOT NULL,
		FIELDSELECTOR    VARCHAR(MAX) NOT NULL,
		DISPLAYNAME      VARCHAR(MAX) NOT NULL,
		FIELDTYPE        VARCHAR(MAX) NOT NULL,
		DATATYPE         VARCHAR(MAX) NOT NULL,
		FIELDID          VARCHAR(MAX) NOT NULL,
		ITEMPOSITION     INT NULL,
		[VALUE]          VARCHAR(MAX) NULL
	);

	/*
		TODO:
			Docs not yet encountered
			DocLists not yet encountered
			PersonLinks not yet encountered
			PersonLinkLists not yet encountered
			StringLists not yet encountered
			Comments not yet encountered (Missing from current script)
			Several FieldTypes not yet encountered (Missing from ID list used in the filter below "PF.FIELDTYPE IN")
	*/

	WITH CONTACTTABFIELDS
		 AS (SELECT 
				 PF.ID AS PERSONFIELDID,
				 PT.TITLE AS FIELDTABNAME,
				 PFS.TITLE AS FIELDSETNAME,
				 CONCAT('(',RIGHT('0000' + CONVERT(VARCHAR(20),PFS.POSITION),4),',',RIGHT('0000' + CONVERT(VARCHAR(20),PF.POSITION),4),')') AS FIELDPOSITION,
				 PF.SELECTOR AS FIELDSELECTOR,
				 PF.TITLE AS DISPLAYNAME,
				 PF.FIELDTYPE,
				 DETAILSJSON,
				 JSON_VALUE(PF.DETAILSJSON,'$.defaultValue') AS DEFAULTVALUE
			 FROM PERSONTAB AS PT
			 INNER JOIN PERSONFIELDSET AS PFS
				 ON PFS.PERSONTABID = PT.ID
			 INNER JOIN PERSONFIELD AS PF
				 ON PF.PERSONFIELDSETID = PFS.ID
			 /*Including only field types that we can migrate into*/
			 WHERE PF.FIELDTYPE IN
				 (
				 01,	/*Integer = 1				->	PersonDataInteger	*/
				 02,	/*Currency = 2				->	PersonDataDecimal	*/
				 03,	/*String = 3				->	PersonDataString	*/
				 04,	/*Date = 4					->	PersonDataDate		*/
				 05,	/*Boolean = 5				->	PersonDataBoolean	*/
				 06,	/*Text = 6					->	PersonDataString	*/
				 07,	/*PersonLink = 7			->	PersonDataPersonLink*/
				 08,	/*Doc = 8					->	PersonDataDoc		*/
				 09,	/*Dropdown = 9				->	PersonDataString	*/
				 11,	/*DocList = 11				->	PersonDataDoc		*/
				 13,	/*PlainDecimal = 13			->	PersonDataDecimal	*/
				 14,	/*Percent = 14				->	PersonDataDecimal	*/
				 17,	/*TextLarge = 17			->	PersonDataString	*/
				 24,	/*StringList = 24			->	PersonDataString	*/
				 25,	/*PersonList = 25			->	PersonDataPersonLink*/
				 26,	/*MultiSelectList = 26		->	PersonDataString	*/
				 /*There are new Field Types that are missing from this list that came with the new Custom Contacts release*/
				 2051/*Switch = 2051				->	PersonDataBoolean	*/
				 ))
		 INSERT INTO DBO.__FV_CONTACTCUSTOMFIELDMETADATA
		 (
			 PERSONID,
			 TAB,
			 FIELDPOSITION,
			 FIELDSELECTOR,
			 DISPLAYNAME,
			 FIELDTYPE,
			 DATATYPE,
			 FIELDID,
			 ITEMPOSITION,
			 [VALUE]
		 )
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'BOOLEAN' AS FIELDTYPE,
			 'BIT' AS DATATYPE,
			 F.PERSONFIELDID,
			 NULL AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ISNULL(D.VALUE,CONVERT(BIT,F.DEFAULTVALUE))) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATABOOLEAN AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 WHERE F.FIELDTYPE IN
			 (
			 5,
			 2051
			 )
		 UNION
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'DATE' AS FIELDTYPE,
			 'DATETIME' AS DATATYPE,
			 F.PERSONFIELDID,
			 NULL AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ISNULL(D.VALUE,CONVERT(DATETIME,F.DEFAULTVALUE))) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATADATE AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 WHERE F.FIELDTYPE = 4
		 UNION
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'DECIMAL' AS FIELDTYPE,
			 'DECIMAL(18,2)' AS DATATYPE,
			 F.PERSONFIELDID,
			 NULL AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ISNULL(D.VALUE,CONVERT(DECIMAL(18,2),F.DEFAULTVALUE))) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATADECIMAL AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 WHERE F.FIELDTYPE IN
			 (
			 2,
			 13,
			 14
			 )
		 UNION
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'DOC' AS FIELDTYPE,
			 'VARCHAR(MAX)' AS DATATYPE,
			 F.PERSONFIELDID,
			 D.ITEMPOSITION AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ND.DOCEXTERNALID) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATADOC AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 LEFT JOIN PT1.DOCUMENTS AS ND
			 ON ND.DOCEXTERNALID = D.DOCID
		 WHERE F.FIELDTYPE IN
			 (
			 8,
			 11
			 )
		 UNION
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'INTEGER' AS FIELDTYPE,
			 'INT' AS DATATYPE,
			 F.PERSONFIELDID,
			 NULL AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ISNULL(D.VALUE,CONVERT(INT,F.DEFAULTVALUE))) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATAINTEGER AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 WHERE F.FIELDTYPE = 1
		 UNION
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'PERSONLINK' AS FIELDTYPE,
			 'VARCHAR(MAX)' AS DATATYPE,
			 F.PERSONFIELDID,
			 D.ITEMPOSITION AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ND.CONTACTCUSTOMEXTERNALID) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATAPERSONLINK AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 LEFT JOIN PT1.CONTACTSCUSTOM__CONTACTINFO AS ND
			 ON ND.CONTACTCUSTOMEXTERNALID = D.RELATEDPERSONID
		 WHERE F.FIELDTYPE IN
			 (
			 7,
			 25
			 )
		 UNION
		 SELECT 
			 D.PERSONID,
			 F.FIELDTABNAME,
			 F.FIELDPOSITION,
			 F.FIELDSELECTOR,
			 F.DISPLAYNAME,
			 'STRING' AS FIELDTYPE,
			 'NVARCHAR(MAX)' AS DATATYPE,
			 F.PERSONFIELDID,
			 D.ITEMPOSITION AS ITEMPOSITION,
			 CONVERT(VARCHAR(MAX),ISNULL(D.VALUE,F.DEFAULTVALUE)) AS FIELDVALUE
		 FROM CONTACTTABFIELDS AS F
		 LEFT JOIN PERSONDATASTRING AS D
			 ON D.PERSONFIELDID = F.PERSONFIELDID
		 WHERE F.FIELDTYPE IN
			 (
			 3,
			 6,
			 9,
			 17,
			 24,
			 26
			 )
		 ORDER BY 
			 FIELDPOSITION,
			 FIELDVALUE;

	/*Output Data Report for all Tabs*/
	SELECT 
		TAB,
		COUNT(DISTINCT FIELDSELECTOR) AS FIELDCOUNT,
		COUNT(*) AS RECORDCOUNT,
		SUM(IIF(VALUE IS NOT NULL,1.0,0.0)) / COUNT(*) AS NOTNULLPERCENT
	FROM __FV_CONTACTCUSTOMFIELDMETADATA
	GROUP BY 
		TAB
	ORDER BY 
		TAB;
END;
GO