/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[CustomSectionID]
      ,[Name]
      ,[CustomFieldType]
      ,[InternalName]
      ,[Row]
      ,[OrderInRow]
      ,[Notes]
      ,[FieldSelector]
      ,[CustomActionButtonType]
      ,[IsObsolete]
      ,[IsLocked]
      ,[Instructions]
      ,[PersonFilter]
      ,[CustomFieldDetailsJson]
      ,[IsRequired]
  FROM [7119_FedEx_II_r2].[dbo].[CustomField]