/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
     -- ,[CustomProjectTypeID]
      --,[CustomSectionType]
      ,[Name]
      --,[Position]
      --,[Icon]
      --,[IsCollection]
      --,[InternalName]
      --,[Notes]
      --,[MainLeftFieldID]
      --,[MainRightFieldID]
      --,[TotalMainRight]
      --,[DefaultSortFieldID]
      --,[DefaultSortIsAsc]
      --,[SectionSelector]
      --,[IsLockedForNonProjectAdmin]
      --,[DefaultVisibility]
  FROM [7119_FedEx_II_r2].[dbo].[CustomSection]